// AGNEX Technology — AI Slop Website Auditor
// High-Fidelity Realistic Demonstration Dataset (Demo Mode)

import { FullAuditReport } from './types';
import { computeTransparentScores } from './scoringEngine';

export function getDemoAuditReport(): FullAuditReport {
  const demoPages = [
    {
      id: 'page-1',
      url: 'https://demo-saas-enterprise.io/',
      path: '/',
      title: 'NextGen Cloud Platform — Intelligent Enterprise Scale',
      wordCount: 840,
      characterCount: 5200,
      overallQuality: 74,
      aiLikelihood: 38,
      aiSlopRisk: 32,
      originalityScore: 68,
      seoScore: 85,
      readabilityScore: 78,
      technicalScore: 92,
      isThinContent: false,
      lexicalDiversity: 0.44,
      detectedSignals: [
        {
          patternId: 'intro_fast_paced',
          label: "Formulaic Opening ('In today's fast-paced...')",
          category: 'generic_intro' as const,
          snippets: ["In today's fast-paced digital landscape, enterprises must adapt..."],
          severity: 'high' as const,
          explanation: 'Overused boilerplate opening phrase frequently generated by language models.'
        },
        {
          patternId: 'transition_delve_tapestry',
          label: "AI Hallmark Vocabulary ('Delve', 'Tapestry')",
          category: 'formulaic_transition' as const,
          snippets: ['...navigating the rich tapestry of microservices architecture...'],
          severity: 'high' as const,
          explanation: 'Statistical LLM hallmark token rarely present in native engineering prose.'
        }
      ],
      h1Tags: ['NextGen Cloud Platform for High-Velocity Modern Teams'],
      h2Count: 5,
      metaDescription: 'Scalable cloud infrastructure platform designed to accelerate delivery and unify deployments.',
      hasCanonical: true,
      hasSchemaMarkup: true,
      hasOpenGraph: true,
      hasTwitterCard: true,
      imagesMissingAlt: 1,
      totalImages: 6,
      httpStatus: 200,
      isHttps: true,
      hasMobileViewport: true,
      loadLatencyMs: 142,
      contentLengthBytes: 34500,
      problems: [
        'Formulaic AI introduction in hero narrative',
        'Image missing descriptive alt attribute in feature matrix'
      ]
    },
    {
      id: 'page-2',
      url: 'https://demo-saas-enterprise.io/blog/unlocking-the-ai-revolution',
      path: '/blog/unlocking-the-ai-revolution',
      title: 'Unlocking the Power of Artificial Intelligence: A Comprehensive Guide',
      wordCount: 1250,
      characterCount: 7800,
      overallQuality: 42,
      aiLikelihood: 88,
      aiSlopRisk: 82,
      originalityScore: 28,
      seoScore: 70,
      readabilityScore: 62,
      technicalScore: 90,
      isThinContent: true,
      thinContentReason: 'High word count (1250) but extremely low information density; circular definitions with zero novel data or case study benchmarks.',
      lexicalDiversity: 0.29,
      detectedSignals: [
        {
          patternId: 'intro_fast_paced',
          label: "Formulaic Opening ('In today's fast-paced...')",
          category: 'generic_intro' as const,
          snippets: ["In today's rapidly evolving digital age, AI is transforming..."],
          severity: 'high' as const,
          explanation: 'Generic AI opening trope.'
        },
        {
          patternId: 'intro_delve_explore',
          label: "Generic Intent Boilerplate ('In this comprehensive guide, we delve')",
          category: 'generic_intro' as const,
          snippets: ['In this comprehensive guide, we will delve into the revolutionary potential...'],
          severity: 'medium' as const,
          explanation: 'Textbook LLM thesis statement announcing obvious intent.'
        },
        {
          patternId: 'outro_in_conclusion',
          label: "Formulaic Conclusion ('In conclusion, by unlocking...')",
          category: 'generic_outro' as const,
          snippets: ['In conclusion, AI serves as an indispensable beacon of efficiency...'],
          severity: 'medium' as const,
          explanation: 'Mechanical essay wrap-up that restates headings without actionable synthesis.'
        },
        {
          patternId: 'vague_industry_leaders',
          label: "Unsupported Authority ('Many experts agree...')",
          category: 'lack_of_evidence' as const,
          snippets: ['Many experts agree that intelligent automation will pave the way...'],
          severity: 'high' as const,
          explanation: 'Weasel words attributing broad assertions to unnamed sources without verifiable citations.'
        }
      ],
      h1Tags: ['Unlocking the Power of Artificial Intelligence: A Comprehensive Guide'],
      h2Count: 6,
      metaDescription: 'Explore the full potential of artificial intelligence in our in-depth comprehensive guide.',
      hasCanonical: true,
      hasSchemaMarkup: false,
      hasOpenGraph: true,
      hasTwitterCard: false,
      imagesMissingAlt: 2,
      totalImages: 3,
      httpStatus: 200,
      isHttps: true,
      hasMobileViewport: true,
      loadLatencyMs: 195,
      contentLengthBytes: 42000,
      problems: [
        'Severe AI-slop risk: 4 distinct formulaic prompt pattern categories detected',
        'Thin information density despite high word count',
        'Unsupported authority assertions without verifiable citations',
        'Missing JSON-LD structured data and Twitter card'
      ]
    },
    {
      id: 'page-3',
      url: 'https://demo-saas-enterprise.io/services/cloud-migration-austin',
      path: '/services/cloud-migration-austin',
      title: 'Cloud Migration Services in Austin, TX — NextGen',
      wordCount: 310,
      characterCount: 1950,
      overallQuality: 48,
      aiLikelihood: 65,
      aiSlopRisk: 60,
      originalityScore: 35,
      seoScore: 68,
      readabilityScore: 70,
      technicalScore: 94,
      isThinContent: true,
      thinContentReason: 'Programmatic doorway page template: Under 350 words with swapped geo-entity token.',
      lexicalDiversity: 0.35,
      detectedSignals: [
        {
          patternId: 'vague_game_changer',
          label: "Superlative Hyperbole ('Game-changer')",
          category: 'vague_claim' as const,
          snippets: ['...our revolutionary cloud migration framework is a true game-changer for Austin enterprises...'],
          severity: 'medium' as const,
          explanation: 'Superlative marketing puffery devoid of technical architecture detail.'
        }
      ],
      h1Tags: ['Premier Cloud Migration Services in Austin, TX'],
      h2Count: 2,
      metaDescription: 'Top-rated cloud migration and modern architecture consulting for Austin businesses.',
      hasCanonical: true,
      hasSchemaMarkup: false,
      hasOpenGraph: true,
      hasTwitterCard: true,
      imagesMissingAlt: 0,
      totalImages: 1,
      httpStatus: 200,
      isHttps: true,
      hasMobileViewport: true,
      loadLatencyMs: 110,
      contentLengthBytes: 19800,
      problems: [
        'Duplicate template clustering with /services/cloud-migration-dallas',
        'Thin content: Lacks case study evidence or architectural specifications'
      ]
    },
    {
      id: 'page-4',
      url: 'https://demo-saas-enterprise.io/services/cloud-migration-dallas',
      path: '/services/cloud-migration-dallas',
      title: 'Cloud Migration Services in Dallas, TX — NextGen',
      wordCount: 315,
      characterCount: 1980,
      overallQuality: 47,
      aiLikelihood: 66,
      aiSlopRisk: 61,
      originalityScore: 34,
      seoScore: 68,
      readabilityScore: 70,
      technicalScore: 94,
      isThinContent: true,
      thinContentReason: 'Programmatic doorway page template: 92% identical to Austin service page.',
      lexicalDiversity: 0.35,
      detectedSignals: [
        {
          patternId: 'vague_game_changer',
          label: "Superlative Hyperbole ('Game-changer')",
          category: 'vague_claim' as const,
          snippets: ['...our revolutionary cloud migration framework is a true game-changer for Dallas enterprises...'],
          severity: 'medium' as const,
          explanation: 'Identical phrasing to Austin variant.'
        }
      ],
      h1Tags: ['Premier Cloud Migration Services in Dallas, TX'],
      h2Count: 2,
      metaDescription: 'Top-rated cloud migration and modern architecture consulting for Dallas businesses.',
      hasCanonical: true,
      hasSchemaMarkup: false,
      hasOpenGraph: true,
      hasTwitterCard: true,
      imagesMissingAlt: 0,
      totalImages: 1,
      httpStatus: 200,
      isHttps: true,
      hasMobileViewport: true,
      loadLatencyMs: 108,
      contentLengthBytes: 19900,
      problems: [
        'Duplicate template clustering with /services/cloud-migration-austin',
        'Thin content: Programmatic doorway page'
      ]
    },
    {
      id: 'page-5',
      url: 'https://demo-saas-enterprise.io/engineering/event-driven-cqrs-architecture',
      path: '/engineering/event-driven-cqrs-architecture',
      title: 'Engineering Deep Dive: Zero-Downtime Event-Driven CQRS Architecture',
      wordCount: 1420,
      characterCount: 9400,
      overallQuality: 92,
      aiLikelihood: 12,
      aiSlopRisk: 14,
      originalityScore: 94,
      seoScore: 91,
      readabilityScore: 82,
      technicalScore: 96,
      isThinContent: false,
      lexicalDiversity: 0.58,
      detectedSignals: [], // No slop detected! High-signal engineering writing
      h1Tags: ['Engineering Zero-Downtime CQRS with Kafka and Event Sourcing'],
      h2Count: 7,
      metaDescription: 'How our engineering team scaled event-driven state hydration to 45,000 writes/sec with strict idempotency and partitioned consumer groups.',
      hasCanonical: true,
      hasSchemaMarkup: true,
      hasOpenGraph: true,
      hasTwitterCard: true,
      imagesMissingAlt: 0,
      totalImages: 4,
      httpStatus: 200,
      isHttps: true,
      hasMobileViewport: true,
      loadLatencyMs: 165,
      contentLengthBytes: 52000,
      problems: []
    }
  ];

  const demoDuplicateClusters = [
    {
      id: 'cluster-1',
      similarityPercentage: 92,
      representativeTheme: 'Geo-Targeted Cloud Migration Doorway Pages',
      explanation: '2 pages exhibit 92% identical text shingles. These are programmatically generated location landing pages with identical sentence structures and single city name substitutions.',
      pages: [
        {
          url: 'https://demo-saas-enterprise.io/services/cloud-migration-austin',
          path: '/services/cloud-migration-austin',
          title: 'Cloud Migration Services in Austin, TX',
          snippet: 'Looking for the premier cloud migration partner in Austin, TX? Our revolutionary cloud migration framework is a true game-changer...'
        },
        {
          url: 'https://demo-saas-enterprise.io/services/cloud-migration-dallas',
          path: '/services/cloud-migration-dallas',
          title: 'Cloud Migration Services in Dallas, TX',
          snippet: 'Looking for the premier cloud migration partner in Dallas, TX? Our revolutionary cloud migration framework is a true game-changer...'
        }
      ]
    }
  ];

  return computeTransparentScores(
    demoPages,
    demoDuplicateClusters,
    'https://demo-saas-enterprise.io',
    true // isDemo flag = true
  );
}
