// AGNEX Technology — AI Slop Website Auditor
// Heuristic Multi-Signal Content & AI-Slop Detection Engine

import { SlopSignalMatch, IssuePriority } from './types';

interface SignalPattern {
  id: string;
  label: string;
  category: SlopSignalMatch['category'];
  regex: RegExp;
  severity: IssuePriority;
  explanation: string;
}

// Curated enterprise catalog of formulaic AI-slop indicators
const SLOP_PATTERNS: SignalPattern[] = [
  // 1. Generic AI Introductions
  {
    id: 'intro_fast_paced',
    label: "Formulaic Opening ('In today's fast-paced...')",
    category: 'generic_intro',
    regex: /\b(in today(?:'s|s)? (?:fast[- ]paced|rapidly (?:evolving|changing)|digital|modern) (?:world|landscape|era|age))\b/i,
    severity: 'high',
    explanation: 'Overused boilerplate opening phrase frequently generated by language models lacking contextual grounding.'
  },
  {
    id: 'intro_delve_explore',
    label: "Generic Intent Boilerplate ('In this article, we will delve/explore')",
    category: 'generic_intro',
    regex: /\b(in this (?:article|guide|post|comprehensive guide),? we (?:will|shall) (?:delve into|explore|take a closer look at|uncover))\b/i,
    severity: 'medium',
    explanation: 'Textbook LLM thesis statement announcing obvious intent without direct BLUF substance.'
  },
  {
    id: 'intro_important_to_note',
    label: "Formulaic Premise ('It is important to remember/note that')",
    category: 'generic_intro',
    regex: /\b(it(?:'s| is) (?:crucial|vital|important|essential) to (?:remember|note|keep in mind|understand) that)\b/i,
    severity: 'low',
    explanation: 'Passive throat-clearing phrasing characteristic of cautious AI outputs.'
  },

  // 2. Generic AI Conclusions & Summaries
  {
    id: 'outro_in_conclusion',
    label: "Formulaic Conclusion ('In conclusion / All in all...')",
    category: 'generic_outro',
    regex: /\b(in conclusion,?|all in all,?|to sum up,?|in summary,?|ultimately, the journey to|as we have seen,)\b/i,
    severity: 'medium',
    explanation: 'Mechanical essay-style wrap-up paragraph that restates previous headings without offering novel synthesis.'
  },
  {
    id: 'outro_unlock_potential',
    label: "Cliche Call-to-Action ('Unlock the full potential of...')",
    category: 'generic_outro',
    regex: /\b(unlock(?:ing)? the (?:full )?potential of|take your [a-z]+ to the next level|pave the way for a brighter)\b/i,
    severity: 'high',
    explanation: 'Generic marketing cliché common in low-information marketing copy generated via prompt templates.'
  },

  // 3. Formulaic Transitional Connectors
  {
    id: 'transition_delve_tapestry',
    label: "AI Hallmark Vocabulary ('Delve', 'Tapestry', 'Beacon')",
    category: 'formulaic_transition',
    regex: /\b(delve into|rich tapestry|beacon of|testament to|kaleidoscope|ever-evolving landscape)\b/i,
    severity: 'high',
    explanation: 'High-frequency statistical LLM tokens rarely used in authentic engineering or domain-expert writing.'
  },
  {
    id: 'transition_stacking',
    label: "Consecutive Dense Transitionals ('Furthermore... Moreover...')",
    category: 'formulaic_transition',
    regex: /\b(furthermore|moreover|additionally|consequently|notwithstanding)\b/i,
    severity: 'low',
    explanation: 'Over-reliance on formal schoolbook conjunctive adverbs indicating robotic paragraph structuring.'
  },

  // 4. Vague Claims & Missing Specificity
  {
    id: 'vague_industry_leaders',
    label: "Unsupported Authority ('Many experts agree / Studies show...')",
    category: 'lack_of_evidence',
    regex: /\b(many (?:experts|studies|companies|leaders) (?:agree|show|suggest|believe)|it is widely (?:known|accepted) that)\b/i,
    severity: 'high',
    explanation: 'Weasel words attributing statements to unnamed authorities without citations or verifiable data.'
  },
  {
    id: 'vague_game_changer',
    label: "Superlative Hyperbole ('Game-changer', 'Revolutionary')",
    category: 'vague_claim',
    regex: /\b(a game[- ]changer|revolutionary breakthrough|paradigm shift|unprecedented efficiency)\b/i,
    severity: 'medium',
    explanation: 'Unsubstantiated marketing puffery unsupported by technical benchmarks or empirical metrics.'
  },

  // 5. Filler & Low Information Density
  {
    id: 'filler_serves_as',
    label: "Wordy Filler ('Serves as a testament / acts as a')",
    category: 'filler',
    regex: /\b(serves as a (?:testament|reminder|catalyst)|acts as an indispensable)\b/i,
    severity: 'medium',
    explanation: 'Padding phrases used to inflate word counts without increasing informational utility.'
  }
];

export interface AnalyzedContentSignals {
  wordCount: number;
  characterCount: number;
  lexicalDiversity: number;
  aiLikelihood: number;
  aiSlopRisk: number;
  originalityScore: number;
  readabilityScore: number;
  contentQuality: number;
  isThinContent: boolean;
  thinContentReason?: string;
  detectedSignals: SlopSignalMatch[];
  problems: string[];
}

/**
 * Analyzes clean extracted text from a web page for AI-slop indicators,
 * original voice markers, lexical diversity, and information density.
 */
export function analyzePageText(plainText: string, title: string = ''): AnalyzedContentSignals {
  const clean = plainText.replace(/\s+/g, ' ').trim();
  const words = clean.toLowerCase().match(/\b[a-z0-9_-]+\b/g) || [];
  const wordCount = words.length;
  const characterCount = clean.length;

  // Empty or tiny page guard
  if (wordCount < 40) {
    return {
      wordCount,
      characterCount,
      lexicalDiversity: 0.1,
      aiLikelihood: 10,
      aiSlopRisk: 25,
      originalityScore: 30,
      readabilityScore: 50,
      contentQuality: 20,
      isThinContent: true,
      thinContentReason: 'Severe thin content: Page contains fewer than 40 words with negligible informational substance.',
      detectedSignals: [],
      problems: ['Severe thin content: Insufficient copy for user search intent']
    };
  }

  // 1. Lexical Diversity (Type-Token Ratio)
  const uniqueWords = new Set(words);
  const lexicalDiversity = Math.min(1, Math.round((uniqueWords.size / wordCount) * 100) / 100);

  // 2. Pattern Matching across clean text
  const detectedSignals: SlopSignalMatch[] = [];
  const matchedCategories = new Set<string>();
  const problems: string[] = [];

  SLOP_PATTERNS.forEach(pat => {
    const matches = clean.match(new RegExp(pat.regex, 'gi'));
    if (matches && matches.length > 0) {
      const snippets = Array.from(new Set(matches)).slice(0, 3);
      detectedSignals.push({
        patternId: pat.id,
        label: pat.label,
        category: pat.category,
        snippets,
        severity: pat.severity,
        explanation: pat.explanation
      });
      matchedCategories.add(pat.category);
      problems.push(`${pat.label} (${snippets.length} instance${snippets.length > 1 ? 's' : ''})`);
    }
  });

  // 3. First-Hand Experience & Evidence Signals (Counter-weights to AI-slop)
  const firstHandMarkers = /\b(we (?:built|tested|measured|implemented|engineered|observed)|our (?:benchmarks|team|data|findings|architecture)|in our (?:experience|tests|trials)|fig\.|table \d|cvss|rfc[- ]\d+)\b/gi;
  const evidenceMatches = clean.match(firstHandMarkers) || [];
  const evidenceScore = Math.min(30, evidenceMatches.length * 6);

  // 4. Repeated Paragraph / Sentence Boilerplate Detection
  const sentences = clean.split(/[.!?]+/).map(s => s.trim()).filter(s => s.length > 20);
  const sentenceStarts = sentences.map(s => s.split(' ').slice(0, 3).join(' ').toLowerCase());
  const sentenceStartCounts = new Map<string, number>();
  let repetitiveStartCount = 0;

  sentenceStarts.forEach(start => {
    const c = (sentenceStartCounts.get(start) || 0) + 1;
    sentenceStartCounts.set(start, c);
    if (c >= 3) repetitiveStartCount++;
  });

  if (repetitiveStartCount >= 2) {
    problems.push(`Monotonous sentence construction: ${repetitiveStartCount} sentences share repetitive 3-word opening sequences.`);
  }

  // 5. Compute AI Likelihood & AI Slop Risk (Multi-Signal)
  // Base raw score starts from detected signal categories and severity
  let rawSlopScore = 0;
  detectedSignals.forEach(sig => {
    if (sig.severity === 'critical') rawSlopScore += 25;
    else if (sig.severity === 'high') rawSlopScore += 18;
    else if (sig.severity === 'medium') rawSlopScore += 10;
    else rawSlopScore += 5;
  });

  if (repetitiveStartCount >= 2) rawSlopScore += 12;
  if (lexicalDiversity < 0.38) rawSlopScore += 15; // Low vocabulary variation

  // Counterbalance: genuine empirical citations, code snippets, or original case study data reduce risk
  rawSlopScore = Math.max(0, rawSlopScore - evidenceScore);

  // Calibrate final scores:
  // AI-slop risk: 0-100 (Higher = worse)
  const aiSlopRisk = Math.min(95, Math.max(5, Math.round(rawSlopScore)));

  // AI-generated content likelihood: 0-100% (Probability estimate)
  let aiLikelihood = Math.min(92, Math.max(8, Math.round(rawSlopScore * 1.1)));
  if (detectedSignals.length === 0 && evidenceMatches.length > 2) {
    aiLikelihood = Math.min(15, aiLikelihood);
  }

  // Originality Score: 0-100 (Higher = better)
  let originalityScore = Math.round(
    (lexicalDiversity * 50) +
    (evidenceScore * 1.2) -
    (detectedSignals.length * 7) +
    35
  );
  originalityScore = Math.min(98, Math.max(12, originalityScore));

  // Readability Score (Approximated Flesch Reading Ease based on word and sentence length)
  const avgSentenceLength = sentences.length > 0 ? wordCount / sentences.length : 20;
  let readabilityScore = Math.round(100 - (avgSentenceLength * 1.8));
  if (readabilityScore < 20) readabilityScore = 30;
  if (readabilityScore > 95) readabilityScore = 92;

  // Thin Content Evaluation (Information density vs word count)
  let isThinContent = false;
  let thinContentReason: string | undefined;

  if (wordCount < 180 && detectedSignals.length > 0) {
    isThinContent = true;
    thinContentReason = `Thin content with high formulaic phrasing: Page is under 180 words and relies primarily on generic boilerplate.`;
    problems.push('Thin content: Low informational value below 180 words');
  } else if (wordCount < 120 && evidenceMatches.length === 0) {
    isThinContent = true;
    thinContentReason = `Shallow content length: Under 120 words with minimal structural context.`;
    problems.push('Thin content: Page lacks depth for meaningful user query satisfaction');
  } else if (lexicalDiversity < 0.32 && wordCount > 400) {
    isThinContent = true;
    thinContentReason = `Low information density: High word count (${wordCount}) but repetitive vocabulary and circular arguments.`;
    problems.push('Padded / Fluff content: High word count with low informational density');
  }

  // Content Quality: Holistic 0-100
  let qualityPenalty = (aiSlopRisk * 0.45) + (isThinContent ? 30 : 0) + (problems.length * 4);
  let contentQuality = Math.round(100 - qualityPenalty + (evidenceScore * 0.6));
  contentQuality = Math.min(96, Math.max(10, contentQuality));

  return {
    wordCount,
    characterCount,
    lexicalDiversity,
    aiLikelihood,
    aiSlopRisk,
    originalityScore,
    readabilityScore,
    contentQuality,
    isThinContent,
    thinContentReason,
    detectedSignals,
    problems
  };
}
