/**
 * AGNEX Technology — AI Slop Website Auditor & Content Intelligence API
 * Route: /api/audit (Rewritten from /api/v1/audit via vercel.json)
 * Security: SSRF hardened, private IP blocking, 8s timeout, 5MB response size limit
 */

import * as cheerio from 'cheerio';

// SSRF Denylist
const BLOCKED_HOSTNAMES = new Set([
  'localhost',
  '127.0.0.1',
  '0.0.0.0',
  '::1',
  'metadata.google.internal',
  'instance-data',
  '169.254.169.254'
]);

function validateUrl(rawUrl) {
  if (!rawUrl || typeof rawUrl !== 'string') return { valid: false, error: 'URL is required' };
  let trimmed = rawUrl.trim();
  if (!/^https?:\/\//i.test(trimmed)) trimmed = `https://${trimmed}`;
  
  let parsed;
  try {
    parsed = new URL(trimmed);
  } catch {
    return { valid: false, error: 'Malformed URL format' };
  }

  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    return { valid: false, error: 'Only HTTP/HTTPS permitted' };
  }

  const hostname = parsed.hostname.toLowerCase();
  if (BLOCKED_HOSTNAMES.has(hostname) || hostname.endsWith('.local') || hostname.endsWith('.internal')) {
    return { valid: false, error: 'Private or internal addresses are prohibited' };
  }

  const ipMatch = hostname.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);
  if (ipMatch) {
    const [_, o1, o2, o3, o4] = ipMatch.map(Number);
    if (o1 === 127 || o1 === 10 || (o1 === 172 && o2 >= 16 && o2 <= 31) || (o1 === 192 && o2 === 168) || (o1 === 169 && o2 === 254) || o1 === 0) {
      return { valid: false, error: 'Private RFC1918 / Cloud metadata IP ranges are prohibited' };
    }
  }

  if (hostname.startsWith('[') && hostname.endsWith(']')) {
    const v6 = hostname.slice(1, -1).toLowerCase();
    if (v6 === '::1' || v6.startsWith('fe80:') || v6.startsWith('fc00:') || v6.startsWith('fd00:')) {
      return { valid: false, error: 'Private IPv6 addresses are prohibited' };
    }
  }

  return { valid: true, url: parsed.origin + parsed.pathname, parsed };
}

// SLOP PATTERNS for Node runtime
const SLOP_PATTERNS = [
  {
    id: 'intro_fast_paced',
    label: "Formulaic Opening ('In today's fast-paced...')",
    category: 'generic_intro',
    regex: /\b(in today(?:'s|s)? (?:fast[- ]paced|rapidly (?:evolving|changing)|digital|modern) (?:world|landscape|era|age))\b/i,
    severity: 'high',
    explanation: 'Overused boilerplate opening phrase frequently generated by language models.'
  },
  {
    id: 'intro_delve_explore',
    label: "Generic Intent Boilerplate ('In this article, we delve/explore')",
    category: 'generic_intro',
    regex: /\b(in this (?:article|guide|post|comprehensive guide),? we (?:will|shall) (?:delve into|explore|take a closer look at|uncover))\b/i,
    severity: 'medium',
    explanation: 'Mechanical thesis statement announcing obvious intent.'
  },
  {
    id: 'intro_important_to_note',
    label: "Formulaic Premise ('It is important to remember/note that')",
    category: 'generic_intro',
    regex: /\b(it(?:'s| is) (?:crucial|vital|important|essential) to (?:remember|note|keep in mind|understand) that)\b/i,
    severity: 'low',
    explanation: 'Passive throat-clearing phrasing characteristic of cautious AI outputs.'
  },
  {
    id: 'outro_in_conclusion',
    label: "Formulaic Conclusion ('In conclusion / All in all...')",
    category: 'generic_outro',
    regex: /\b(in conclusion,?|all in all,?|to sum up,?|in summary,?|ultimately, the journey to|as we have seen,)\b/i,
    severity: 'medium',
    explanation: 'Mechanical essay-style wrap-up paragraph.'
  },
  {
    id: 'outro_unlock_potential',
    label: "Cliche Call-to-Action ('Unlock the full potential of...')",
    category: 'generic_outro',
    regex: /\b(unlock(?:ing)? the (?:full )?potential of|take your [a-z]+ to the next level|pave the way for a brighter)\b/i,
    severity: 'high',
    explanation: 'Generic marketing cliché common in low-information copy.'
  },
  {
    id: 'transition_delve_tapestry',
    label: "AI Hallmark Vocabulary ('Delve', 'Tapestry', 'Beacon')",
    category: 'formulaic_transition',
    regex: /\b(delve into|rich tapestry|beacon of|testament to|kaleidoscope|ever-evolving landscape)\b/i,
    severity: 'high',
    explanation: 'Statistical LLM hallmark token rarely present in native engineering prose.'
  },
  {
    id: 'vague_industry_leaders',
    label: "Unsupported Authority ('Many experts agree / Studies show...')",
    category: 'lack_of_evidence',
    regex: /\b(many (?:experts|studies|companies|leaders) (?:agree|show|suggest|believe)|it is widely (?:known|accepted) that)\b/i,
    severity: 'high',
    explanation: 'Weasel words attributing broad assertions to unnamed sources without verifiable citations.'
  },
  {
    id: 'vague_game_changer',
    label: "Superlative Hyperbole ('Game-changer', 'Revolutionary')",
    category: 'vague_claim',
    regex: /\b(a game[- ]changer|revolutionary breakthrough|paradigm shift|unprecedented efficiency)\b/i,
    severity: 'medium',
    explanation: 'Unsubstantiated marketing puffery unsupported by technical benchmarks.'
  }
];

function analyzeText(cleanText) {
  const words = cleanText.toLowerCase().match(/\b[a-z0-9_-]+\b/g) || [];
  const wordCount = words.length;
  if (wordCount < 40) {
    return {
      wordCount,
      characterCount: cleanText.length,
      lexicalDiversity: 0.1,
      aiLikelihood: 10,
      aiSlopRisk: 25,
      originalityScore: 30,
      readabilityScore: 50,
      contentQuality: 20,
      isThinContent: true,
      thinContentReason: 'Fewer than 40 words extracted.',
      detectedSignals: [],
      problems: ['Severe thin content']
    };
  }

  const uniqueWords = new Set(words);
  const lexicalDiversity = Math.min(1, Math.round((uniqueWords.size / wordCount) * 100) / 100);

  const detectedSignals = [];
  const problems = [];
  SLOP_PATTERNS.forEach(pat => {
    const m = cleanText.match(new RegExp(pat.regex, 'gi'));
    if (m && m.length > 0) {
      detectedSignals.push({
        patternId: pat.id,
        label: pat.label,
        category: pat.category,
        snippets: Array.from(new Set(m)).slice(0, 3),
        severity: pat.severity,
        explanation: pat.explanation
      });
      problems.push(`${pat.label} (${m.length} instance${m.length > 1 ? 's' : ''})`);
    }
  });

  const evidenceMatches = cleanText.match(/\b(we (?:built|tested|measured|implemented|engineered|observed)|our (?:benchmarks|team|data)|fig\.|cvss|rfc[- ]\d+)\b/gi) || [];
  const evidenceScore = Math.min(30, evidenceMatches.length * 6);

  let rawSlop = 0;
  detectedSignals.forEach(s => {
    if (s.severity === 'high') rawSlop += 20;
    else if (s.severity === 'medium') rawSlop += 12;
    else rawSlop += 5;
  });
  if (lexicalDiversity < 0.38) rawSlop += 15;
  rawSlop = Math.max(0, rawSlop - evidenceScore);

  const aiSlopRisk = Math.min(95, Math.max(5, Math.round(rawSlop)));
  const aiLikelihood = Math.min(92, Math.max(8, Math.round(rawSlop * 1.1)));
  let originalityScore = Math.round((lexicalDiversity * 50) + (evidenceScore * 1.2) - (detectedSignals.length * 6) + 35);
  originalityScore = Math.min(98, Math.max(15, originalityScore));

  const sentences = cleanText.split(/[.!?]+/).map(s => s.trim()).filter(s => s.length > 20);
  const avgLen = sentences.length > 0 ? wordCount / sentences.length : 20;
  let readabilityScore = Math.min(95, Math.max(30, Math.round(100 - avgLen * 1.8)));

  let isThinContent = false;
  let thinContentReason;
  if (wordCount < 180 && detectedSignals.length > 0) {
    isThinContent = true;
    thinContentReason = 'Under 180 words with formulaic phrases.';
    problems.push('Thin content: Low informational value');
  } else if (wordCount < 100) {
    isThinContent = true;
    thinContentReason = 'Under 100 words.';
    problems.push('Thin content: Minimal depth');
  }

  let qualityPenalty = (aiSlopRisk * 0.45) + (isThinContent ? 25 : 0) + (problems.length * 3);
  let contentQuality = Math.min(96, Math.max(15, Math.round(100 - qualityPenalty + evidenceScore * 0.5)));

  return {
    wordCount,
    characterCount: cleanText.length,
    lexicalDiversity,
    aiLikelihood,
    aiSlopRisk,
    originalityScore,
    readabilityScore,
    contentQuality,
    isThinContent,
    thinContentReason,
    detectedSignals,
    problems
  };
}

async function fetchPage(url) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8000);
  const start = Date.now();

  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: {
        'User-Agent': 'AgnexIntelligenceBot/1.0 (+https://agnextechnology.com)',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
      }
    });
    clearTimeout(timeout);
    const latency = Date.now() - start;

    if (!res.ok) {
      return { status: res.status, latency, html: '', error: `HTTP ${res.status}` };
    }

    const contentType = res.headers.get('content-type') || '';
    if (!contentType.includes('text/html') && !contentType.includes('application/xhtml')) {
      return { status: res.status, latency, html: '', error: 'Non-HTML content' };
    }

    const html = await res.text();
    return { status: res.status, latency, html: html.slice(0, 5000000) };
  } catch (err) {
    clearTimeout(timeout);
    return { status: 0, latency: Date.now() - start, html: '', error: err.message || 'Fetch failed' };
  }
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ status: 'error', message: 'Use POST' });

  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body || {};
    const { url, maxPages = 4 } = body;

    const validation = validateUrl(url);
    if (!validation.valid) {
      return res.status(400).json({ status: 'error', message: validation.error });
    }

    const targetUrl = validation.url;
    const baseOrigin = validation.parsed.origin;

    // 1. Fetch Root Page
    const rootFetch = await fetchPage(targetUrl);
    if (rootFetch.error || !rootFetch.html) {
      return res.status(422).json({
        status: 'error',
        message: `Failed to fetch target URL: ${rootFetch.error || 'No content received'}. Verify the domain is publicly accessible or try Demo Mode.`
      });
    }

    // Parse Root HTML
    const $ = cheerio.load(rootFetch.html);
    $('script, style, noscript, svg, nav, footer, header').remove();
    const rootText = $('body').text().replace(/\s+/g, ' ').trim();
    const rootTitle = $('title').first().text().trim() || validation.parsed.hostname;

    // Discover internal links
    const internalLinks = new Set();
    $('a[href]').each((_, el) => {
      const href = $(el).attr('href');
      if (!href) return;
      try {
        const full = new URL(href, targetUrl);
        if (full.origin === baseOrigin && full.pathname !== validation.parsed.pathname && !full.pathname.match(/\.(png|jpg|jpeg|gif|svg|pdf|zip|css|js)$/i)) {
          internalLinks.add(full.origin + full.pathname);
        }
      } catch {}
    });

    // Crawl discovered pages up to limit
    const toCrawl = Array.from(internalLinks).slice(0, Math.min(maxPages - 1, 3));
    const crawledPages = [];

    // Analyze root page
    const rootAnalysis = analyzeText(rootText);
    crawledPages.push({
      id: 'page-1',
      url: targetUrl,
      path: validation.parsed.pathname || '/',
      title: rootTitle,
      ...rootAnalysis,
      h1Tags: $('h1').map((_, el) => $(el).text().trim()).get(),
      h2Count: $('h2').length,
      metaDescription: $('meta[name="description"]').attr('content') || null,
      hasCanonical: !!$('link[rel="canonical"]').attr('href'),
      hasSchemaMarkup: !!$('script[type="application/ld+json"]').length,
      hasOpenGraph: !!$('meta[property^="og:"]').length,
      hasTwitterCard: !!$('meta[name^="twitter:"]').length,
      imagesMissingAlt: $('img:not([alt]), img[alt=""]').length,
      totalImages: $('img').length,
      httpStatus: rootFetch.status,
      isHttps: targetUrl.startsWith('https://'),
      hasMobileViewport: !!$('meta[name="viewport"]').length,
      loadLatencyMs: rootFetch.latency,
      contentLengthBytes: rootFetch.html.length,
      seoScore: Math.round(
        ($('meta[name="description"]').attr('content') ? 25 : 0) +
        ($('h1').length === 1 ? 25 : 10) +
        ($('link[rel="canonical"]').length ? 25 : 0) +
        ($('meta[property^="og:"]').length ? 25 : 0)
      ),
      technicalScore: targetUrl.startsWith('https://') ? 95 : 75
    });

    // Crawl additional internal pages
    let pageIdx = 2;
    for (const subUrl of toCrawl) {
      const subFetch = await fetchPage(subUrl);
      if (subFetch.html) {
        const sub$ = cheerio.load(subFetch.html);
        sub$('script, style, noscript, svg, nav, footer, header').remove();
        const subText = sub$('body').text().replace(/\s+/g, ' ').trim();
        const subTitle = sub$('title').first().text().trim() || subUrl;
        const subAnalysis = analyzeText(subText);

        crawledPages.push({
          id: `page-${pageIdx++}`,
          url: subUrl,
          path: new URL(subUrl).pathname,
          title: subTitle,
          ...subAnalysis,
          h1Tags: sub$('h1').map((_, el) => sub$(el).text().trim()).get(),
          h2Count: sub$('h2').length,
          metaDescription: sub$('meta[name="description"]').attr('content') || null,
          hasCanonical: !!sub$('link[rel="canonical"]').attr('href'),
          hasSchemaMarkup: !!sub$('script[type="application/ld+json"]').length,
          hasOpenGraph: !!sub$('meta[property^="og:"]').length,
          hasTwitterCard: !!sub$('meta[name^="twitter:"]').length,
          imagesMissingAlt: sub$('img:not([alt]), img[alt=""]').length,
          totalImages: sub$('img').length,
          httpStatus: subFetch.status,
          isHttps: subUrl.startsWith('https://'),
          hasMobileViewport: !!sub$('meta[name="viewport"]').length,
          loadLatencyMs: subFetch.latency,
          contentLengthBytes: subFetch.html.length,
          seoScore: Math.round(
            (sub$('meta[name="description"]').attr('content') ? 25 : 0) +
            (sub$('h1').length === 1 ? 25 : 10) +
            (sub$('link[rel="canonical"]').length ? 25 : 0) +
            (sub$('meta[property^="og:"]').length ? 25 : 0)
          ),
          technicalScore: subUrl.startsWith('https://') ? 95 : 75
        });
      }
    }

    return res.status(200).json({
      status: 'success',
      data: {
        targetUrl,
        pages: crawledPages
      }
    });
  } catch (error) {
    return res.status(500).json({
      status: 'error',
      message: error.message || 'Internal crawler exception'
    });
  }
}
